Repository cph-cachet/carp.core-kotlin, pull requests merged in 2020-07, with the labels that each got.

#141 Fix protocol description from snapshot
  carp.protocols.core/src/commonMain/kotlin/dk/cachet/carp/protocols/domain/StudyProtocol.kt
  carp.protocols.core/src/commonMain/kotlin/dk/cachet/carp/protocols/infrastructure/test/CreateTestObjects.kt
Labels: bug

#143 Add `creationDate` to `AggregateRoot`.
  carp.client.core/src/commonMain/kotlin/dk/cachet/carp/client/domain/StudyRuntime.kt
  carp.client.core/src/commonMain/kotlin/dk/cachet/carp/client/domain/StudyRuntimeSnapshot.kt
  carp.client.core/src/commonTest/kotlin/dk/cachet/carp/client/domain/StudyRuntimeTest.kt
  carp.common/src/commonMain/kotlin/dk/cachet/carp/common/ddd/AggregateRoot.kt
  carp.common/src/commonMain/kotlin/dk/cachet/carp/common/ddd/Snapshot.kt
  carp.deployment.core/src/commonMain/kotlin/dk/cachet/carp/deployment/domain/StudyDeployment.kt
  carp.deployment.core/src/commonMain/kotlin/dk/cachet/carp/deployment/domain/StudyDeploymentSnapshot.kt
  carp.deployment.core/src/commonTest/kotlin/dk/cachet/carp/deployment/domain/StudyDeploymentTest.kt
  carp.protocols.core/src/commonMain/kotlin/dk/cachet/carp/protocols/domain/StudyProtocol.kt
  carp.protocols.core/src/commonMain/kotlin/dk/cachet/carp/protocols/domain/StudyProtocolSnapshot.kt
  carp.studies.core/src/commonMain/kotlin/dk/cachet/carp/studies/domain/Study.kt
  carp.studies.core/src/commonMain/kotlin/dk/cachet/carp/studies/domain/StudySnapshot.kt
  carp.test/package-lock.json
Labels: enhancement, feature

#133 Support deploying custom protocol definitions to devices.
  carp.protocols.core/src/commonMain/kotlin/dk/cachet/carp/protocols/domain/devices/CustomProtocolDevice.kt
  carp.protocols.core/src/commonMain/kotlin/dk/cachet/carp/protocols/domain/tasks/CustomProtocolTask.kt
  carp.protocols.core/src/commonMain/kotlin/dk/cachet/carp/protocols/infrastructure/Serialization.kt
  carp.protocols.core/src/commonTest/kotlin/dk/cachet/carp/protocols/ProtocolsCodeSamples.kt
  carp.protocols.core/src/commonTest/kotlin/dk/cachet/carp/protocols/infrastructure/SerializationTest.kt
  docs/carp-protocols.md
Labels: feature

#145 Add `StudyInvitation.applicationData` to pass infrastructure-specific data to clients.
  carp.deployment.core/src/commonMain/kotlin/dk/cachet/carp/deployment/domain/users/StudyInvitation.kt
  carp.deployment.core/src/commonTest/kotlin/dk/cachet/carp/deployment/application/DeploymentServiceTest.kt
  carp.deployment.core/src/commonTest/kotlin/dk/cachet/carp/deployment/infrastructure/StudyInvitationTest.kt
Labels: feature
